name: Realese and Deploy

on:
  push:
    branches: [ "master" ]

env:
  REGISTRY: aura-dev
  IMAGE_NAME: ${{ github.actor }}/fayno-zno-client:latest

jobs:
    build-image:
        name: Build Docker Image
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build
          run: |
            docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .

    deploy-image:
        needs: build-image
        name: Deploy Docker Image
        runs-on: ubuntu-latest

        steps:
        - name: Install SSH Keys
          run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
        - name: Connect and Pull
          run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker load"
        - name: Cleanup
          run: rm -rf ~/.ssh